services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "192.168.11.103:9090:9090"
    user: nobody
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./config/prometheus/server_targets.yml:/etc/prometheus/server_targets.yml
      - ./config/prometheus/http_websites.yml:/etc/prometheus/http_websites.yml
      # - ./config/prometheus/icmp-websites.yml:/etc/prometheus/icmp-websites.yml
      - ./config/prometheus/rules:/etc/prometheus/rules
      - /home/ubuntu/monitoring/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-admin-api'
    networks:
      - monitoring-net
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:9090/-/healthy || exit 1"]
      interval: 30s
      retries: 3
      start_period: 10s
    extra_hosts:
      - "api-mpp:192.168.11.129"
      - "mpp-api02:192.168.11.127"
      - "nginx-proxy-manager:192.168.11.130"
      - "proxy-nginx-mpp:192.168.11.110"
      - "sistembali-migrasi:192.168.11.72"
      - "db-pdip-prod:192.168.11.63"
      - "db-mpp-prod:192.168.11.121"
      - "minio-pdip-kreatif:192.168.11.106"
      - "minio-mpp:192.168.11.118"
      - "minio-mpp-replica:192.168.11.119"
      - "cms-mpp:192.168.11.178"
      - "pgpool:100.82.8.83"
      - "db-dev01:100.81.1.111"
      - "db-dev02:100.77.74.98"
      - "stg-pdip:192.168.11.131"
      - "stg-kreatif:192.168.11.132"
      - "prod-kreatif:192.168.11.31"

  blackbox-exporter:
    image: "prom/blackbox-exporter:latest"
    container_name: blackbox-exporter
    hostname: "blackbox"
    restart: always
    ports:
    - "192.168.11.103:9115:9115"
    volumes:
    - "./config/blackbox-exporter/blackbox-exporter.yml:/etc/prometheus/blackbox-exporter.yml"
    command:
    - "--config.file=/etc/prometheus/blackbox-exporter.yml"
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "192.168.11.103:3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Ganti password default
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=grafana.sateknologi.id
      - GF_SERVER_ROOT_URL=http://grafana.sateknologi.id/
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=sysadmin.app@sateknologi.id
      - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=sysadmin.app@sateknologi.id
    volumes:
      - /home/ubuntu/monitoring/grafana-storage:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring-net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-S", "http://localhost:3000/api/health"]
      interval: 30s
      retries: 3
      start_period: 10s

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: always
    ports:
      - "192.168.11.103:9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      # - --storage.path=/alertmanager
    env_file:
      - .env
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    networks:
      - monitoring-net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-S", "http://localhost:9093/-/healthy"]
      interval: 30s
      retries: 3
      start_period: 10s

networks:
  monitoring-net:
    external: true
