{
 "title": "Container Dashboard - MPP API",
 "description": "cadvisor + node exporter + docker metrix + prometheus",
 "tags": [
  "cadvisor",
  "docker",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({__name__=~\"container.*\"},instance)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({__name__=~\"container.*\", instance=~\"$host\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host OS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "engine_daemon_engine_info", "legendFormat": "{{os}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_memory_bytes",
     "legendFormat": "{{kernel}}"
    }
   ]
  },
  {
   "title": "CPU Core",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "engine_daemon_engine_cpus_cpus", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Free Swap",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapFree_bytes{job=\"Server Monitoring\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Docker Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "engine_daemon_engine_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Kernel Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "engine_daemon_engine_info", "legendFormat": "{{kernel}}" }
   ]
  },
  {
   "title": "Load 5m",
   "type": "stat",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load5{job=\"Server Monitoring\"}",
     "legendFormat": "load 1m"
    }
   ]
  },
  {
   "title": "Load 1m",
   "type": "stat",
   "gridPos": { "h": 12, "w": 9, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"Server Monitoring\"}",
     "legendFormat": "load 1m"
    }
   ]
  },
  {
   "title": "Free Storage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{fstype=\"ext4\",job=\"Server Monitoring\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=~\"Server Monitoring\"}[2m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{job=~\"Server Monitoring\"}[2m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (nodeexporter) (rate(node_cpu_seconds_total{job=\"Server Monitoring\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"Server Monitoring\"} / (node_memory_MemTotal_bytes{job=\"Server Monitoring\"})))* 100",
     "legendFormat": "RAM Usage"
    }
   ]
  },
  {
   "title": "Network Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"Server Monitoring\",device=\"eth0\"}[1m])*8",
     "legendFormat": "{{device}}_upload"
    }
   ]
  },
  {
   "title": "Network Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"Server Monitoring\",device=\"eth0\"}[1m])*8",
     "legendFormat": "{{device}}_upload"
    }
   ]
  },
  { "title": "Container Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$host\",name=~\"$container\",name=~\".+\"}[5m])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\"$host\",name=~\"$container\",name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory Cached",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{instance=~\"$host\",name=~\"$container\",name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$host\",name=~\"$container\",name=~\".+\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$host\",name=~\"$container\",name=~\".+\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Containers Detail",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{instance=~\"$host\",name=~\"$container\",name=~\".+\"})/86400",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}