global:
  scrape_interval: 15s
  evaluation_interval: 1m
  external_labels:
      monitor: 'Monitoring Server'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  # Self monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for all servers via Tailscale network
  - job_name: 'node-exporter'
    file_sd_configs:
      - files:
        - /etc/prometheus/tailscale_servers.yml
    scrape_interval: 30s

  # MongoDB single instance monitoring
  - job_name: 'mongodb'
    file_sd_configs:
      - files:
        - /etc/prometheus/mongodb_targets.yml
    scrape_interval: 30s

  # Docker container monitoring via cAdvisor
  - job_name: 'docker'
    file_sd_configs:
      - files:
        - /etc/prometheus/docker_targets.yml
    scrape_interval: 30s

  # PM2 services monitoring on remote servers
  - job_name: 'pm2'
    file_sd_configs:
      - files:
        - /etc/prometheus/pm2_targets.yml
    scrape_interval: 30s

