apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus 
  access: proxy
  orgId: 1
  url: http://192.168.11.103:9090
  basicAuth: false 
  isDefault: true
   # <map> fields that will be converted to json and stored in json_data
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
  version: 1
  editable: true
